Disable spell of word under cursor while in insertmode
lewis6991/spellsitter.nvim pull request #60
Opened 2022-02-03 13:28 UTC by seblj

2022-02-15 22:33 UTC, seblj commented
@lewis6991

2022-02-15 22:39 UTC, lewis6991 commented
Sorry. This fell off my radar. Will keep this notification in my inbox and get to this when I can. I want to test a thing or two regarding it.

2022-02-18 11:59 UTC, lewis6991 commented on lua/spellsitter.lua
> +  local cursor = vim.api.nvim_win_get_cursor(0)
This might be more readable:
```lua
local cur_lnum, cur_col = unpack(vim.api.nvim_win_get_cursor(0))
```

2022-02-18 12:02 UTC, lewis6991 requested changes
See comments

2022-02-18 12:40 UTC, merged